CREATE SEQUENCE SEQ_BOARD2;

CREATE TABLE TBL_BOARD2
(
    BOARD_ID            NUMBER
        CONSTRAINT PK_BOARD2 PRIMARY KEY,
    BOARD_TITLE         VARCHAR(200)  NOT NULL,
    BOARD_WRITER        VARCHAR(200)  NOT NULL,
    BOARD_CONTENT       VARCHAR(2000) NOT NULL,
    BOARD_REGISTER_DATE DATE DEFAULT SYSDATE,
    BOARD_UPDATE_DATE   DATE DEFAULT SYSDATE
);

SELECT *
FROM TBL_BOARD2;

INSERT INTO TBL_BOARD2
(BOARD_ID, BOARD_TITLE, BOARD_WRITER, BOARD_CONTENT)
VALUES(SEQ_BOARD2.NEXTVAL, '테스트 제목1', '테스트1', '테스트 내용');

INSERT INTO TBL_BOARD2
(BOARD_ID, BOARD_TITLE, BOARD_WRITER, BOARD_CONTENT)
VALUES(SEQ_BOARD2.NEXTVAL, '테스트 제목2', '테스트2', '테스트 내용');

INSERT INTO TBL_BOARD2
(BOARD_ID, BOARD_TITLE, BOARD_WRITER, BOARD_CONTENT)
VALUES(SEQ_BOARD2.NEXTVAL, '수정된 제목', '수정', '수정된 내용');

INSERT INTO TBL_BOARD2
(BOARD_ID, BOARD_TITLE, BOARD_WRITER, BOARD_CONTENT)
(SELECT SEQ_BOARD2.NEXTVAL, BOARD_TITLE, BOARD_WRITER, BOARD_CONTENT FROM TBL_BOARD2);

SELECT COUNT(*) FROM TBL_BOARD2;