CREATE SEQUENCE SEQ_FILE2;

CREATE TABLE TBL_FILE2(
	FILE_ID NUMBER CONSTRAINT PK_FILE2 PRIMARY KEY,
	FILE_NAME VARCHAR2(1000) NOT NULL,
	FILE_UUID VARCHAR2(500) NOT NULL,
	FILE_SIZE VARCHAR2(1000) NOT NULL,
	FILE_UPLOAD_PATH VARCHAR2(1000) NOT NULL,
	FILE_IS_IMAGE CHAR(1),
	BOARD_ID NUMBER,
	CONSTRAINT FK_FILE2_BOARD2 FOREIGN KEY(BOARD_ID)
	REFERENCES TBL_BOARD2(BOARD_ID) 
);