CREATE SEQUENCE SEQ_REPLY2;

CREATE TABLE TBL_REPLY2(
	REPLY_ID NUMBER CONSTRAINT PK_REPLY2 PRIMARY KEY,
	REPLY_CONTENT VARCHAR2(1000) NOT NULL,
	REPLY_WRITER VARCHAR2(1000) NOT NULL,
	REPLY_REGISTER_DATE DATE DEFAULT SYSDATE,
	REPLY_UPDATE_DATE DATE DEFAULT SYSDATE,
	BOARD_ID NUMBER,
	CONSTRAINT FK_REPLY2_BOARD2 FOREIGN KEY(BOARD_ID)
	REFERENCES TBL_BOARD2(BOARD_ID)
);